CREATE DATABASE LibrarySystemDB;
GO

USE LibrarySystemDB;
GO

CREATE TABLE Authors (
	Id INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL,

	CONSTRAINT Pk_Authors PRIMARY KEY (Id)
)

CREATE TABLE Books (
	Id INT IDENTITY(1,1) NOT NULL,
	AuthorId INT NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	ISBN NVARCHAR(20) NOT NULL,
	PublishedYear INT NOT NULL,

	CONSTRAINT PK_Books PRIMARY KEY (Id),

	CONSTRAINT FK_Books_Authors FOREIGN KEY (AuthorId) REFERENCES Authors(Id) ON DELETE CASCADE
)

CREATE TABLE BookCopies (
	Id INT IDENTITY(1,1) NOT NULL,
	BookId INT NOT NULL,
	IsAvailAble BIT NOT NULL DEFAULT 1,
	RowVersion ROWVERSION NOT NULL,

	CONSTRAINT Pk_BookCopies PRIMARY KEY (Id),
	CONSTRAINT FK_BookCopies_Books FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE CASCADE
)

CREATE TABLE Members (
	Id INT IDENTITY(1,1) NOT NULL,
	MemberNumber NVARCHAR(20) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

	CONSTRAINT Pk_Members PRIMARY KEY (Id),

	CONSTRAINT UQ_Members_MemberNumber UNIQUE (MemberNumber),
	CONSTRAINT UQ_Members_Email UNIQUE (Email)
	
)

CREATE TABLE Loans (
	Id INT IDENTITY(1,1) NOT NULL,
	MemberId INT NOT NULL,
	BookCopyId INT NOT NULL,
	LoanDate DATETIME2 NULL,
	DueDate DATETIME2 NULL,
	ReturnDate DATETIME2 NULL,

	CONSTRAINT Pk_Loans PRIMARY KEY (Id),
	CONSTRAINT Pk_Loans_Members FOREIGN KEY (MemberId) REFERENCES Members(Id),
	CONSTRAINT Pk_Loans_BookCopies FOREIGN KEY (BookCopyId) REFERENCES BookCopies(Id),
	
	CONSTRAINT CK_Loans_DueDate CHECK (DueDate >= LoanDate),
	CONSTRAINT CK_LoansReturnDate CHECK (ReturnDate IS NULL OR ReturnDate >= LoanDate)
)